In [61]:
import pandas as pd
import geobr
import numpy as np
import os

In [62]:
from pathlib import Path

# `cwd`: current directory is straightforward
basepath = str(Path.cwd().parent) + '/public/data'
basepath

'/Users/feliphlvo/access-to-education/public/data'

In [63]:
# Municipalities
municipalities_df = geobr.read_municipality(year=2010)

In [64]:
len(municipalities_df)

5567

In [65]:
municipalities_df.head()

,code_muni,name_muni,code_state,abbrev_state,geometry
0,1100015.0,Alta Floresta D'oeste,11.0,RO,"MULTIPOLYGON (((-62.24620 -11.90149, -62.24151..."
1,1100023.0,Ariquemes,11.0,RO,"MULTIPOLYGON (((-63.13712 -9.78413, -63.09013 ..."
2,1100031.0,Cabixi,11.0,RO,"MULTIPOLYGON (((-60.52408 -13.32137, -60.37161..."
3,1100049.0,Cacoal,11.0,RO,"MULTIPOLYGON (((-61.42679 -11.11376, -61.42900..."
4,1100056.0,Cerejeiras,11.0,RO,"MULTIPOLYGON (((-61.41347 -13.23417, -61.42603..."

In [66]:
# Microregions
microregion_df = geobr.read_micro_region(year=2010, )

In [67]:
microregion_df.head(20)

,code_state,abbrev_state,name_state,code_micro,name_micro,geometry
0,11.0,RO,Rondônia,11007.0,Vilhena,"MULTIPOLYGON (((-60.44294 -11.01572, -60.43794..."
1,11.0,RO,Rondônia,11001.0,Porto Velho,"MULTIPOLYGON (((-63.32721 -7.97672, -62.86662 ..."
2,11.0,RO,Rondônia,11004.0,Ji-Paraná,"MULTIPOLYGON (((-61.57450 -9.72063, -61.57157 ..."
3,11.0,RO,Rondônia,11002.0,Guajará-Mirim,"MULTIPOLYGON (((-65.37724 -10.43117, -65.37505..."
4,11.0,RO,Rondônia,11008.0,Colorado Do Oeste,"MULTIPOLYGON (((-61.47607 -12.46432, -61.46801..."
5,11.0,RO,Rondônia,11006.0,Cacoal,"MULTIPOLYGON (((-61.42731 -10.98755, -61.00059..."
6,11.0,RO,Rondônia,11003.0,Ariquemes,"MULTIPOLYGON (((-62.22055 -8.59088, -62.21053 ..."
7,11.0,RO,Rondônia,11005.0,Alvorada D'oeste,"MULTIPOLYGON (((-63.62702 -11.00502, -63.60993..."
8,12.0,AC,Acre,12002.0,Tarauacá,"MULTIPOLYGON (((-70.05145 -7.84816, -69.44432 ..."
9,12.0,AC,Acre,12003.0,Sena Madureira,"MULTIPOLYGON (((-69.44261 -8.36795, -68.64719 ..."
10,12.0,AC,Acre,12004.0,Rio Branco,"MULTIPOLYGON (((-68.21990 -9.24275, -67.51688 ..."
11,12.0,AC,Acre,12001.0,Cruzeiro Do Sul,"MULTIPOLYGON (((-73.18253 -7.33550, -72.58477 ..."
12,12.0,AC,Acre,12005.0,Brasiléia,"MULTIPOLYGON (((-68.44879 -10.18410, -68.44250..."
13,13.0,AM,Amazônas,13005.0,Tefé,"MULTIPOLYGON (((-65.12451 -2.38965, -65.11559 ..."
14,13.0,AM,Amazônas,13008.0,Rio Preto Da Eva,"MULTIPOLYGON (((-59.93995 0.03489, -59.93328 0..."
15,13.0,AM,Amazônas,13001.0,Rio Negro,"MULTIPOLYGON (((-67.32609 2.02971, -67.31682 2..."
16,13.0,AM,Amazônas,13012.0,Purus,"MULTIPOLYGON (((-62.99193 -4.52308, -62.98952 ..."
17,13.0,AM,Amazônas,13010.0,Parintins,"MULTIPOLYGON (((-58.89546 0.26351, -58.89504 -..."
18,13.0,AM,Amazônas,13007.0,Manaus,"MULTIPOLYGON (((-60.24162 -1.99757, -60.23298 ..."
19,13.0,AM,Amazônas,13013.0,Madeira,"MULTIPOLYGON (((-58.84164 -3.85220, -58.84492 ..."

In [68]:
# Region
region_df = geobr.read_region(year=2010)

In [69]:
len(region_df)

5

In [70]:
# State
state_df = geobr.read_state(year=2010)

In [71]:
len(state_df)

27

In [72]:
# Country
country_df = geobr.read_country(year=2010)

In [73]:
access_df = pd.read_csv(f"{basepath}/access_df.csv")

/var/folders/v6/m0s_jr6d723809xzpzrvx_340000gn/T/ipykernel_51267/3644115942.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  access_df = pd.read_csv(f"{basepath}/access_df.csv")

In [74]:
access_df.columns

Index(['Unnamed: 0', 'sector_id', '3sfca_n_classes', 'e2sfca_n_classes',
       'state', 'n_households', 'n_people', 'avg_monthly_earnings',
       'n_people_15to17_white', 'n_people_15to17_black',
       'n_people_15to17_asian', 'n_people_15to17_parda',
       'n_people_15to17_indigenous', 'n_people_15', 'n_people_16',
       'n_people_17', 'n_people_15_men', 'n_people_16_men', 'n_people_17_men',
       'n_people_15_women', 'n_people_16_women', 'n_people_17_women',
       'n_people_15to17dem', 'n_people_15to17_alternative', 'state_id',
       'state_abbrev', 'city_id', 'city_name', 'district_id', 'district_name',
       'subdistrict_id', 'subdistrict_name', 'neighborhood_name',
       'neighborhood_id', 'geometry', 'microregion_id', 'microregion_name',
       'mesoregion_id', 'mesoregion_name', 'n_people_15to17', 'A', 'Q', 'H',
       'pct_black', 'pct_white', 'pct_indigenous', 'pct_pardos', 'pct_asian',
       'pct_men', 'area', 'density', 'zone_rural', 'zone_urban',
       'region_Midwest', 'region_North', 'region_Northeast', 'region_South',
       'region_Southeast', 'fpl_above', 'fpl_below', 'A_percentile',
       'Q_percentile', 'H_percentile', 'is_outlier', 'std_from_mean',
       'A_clipped', 'H_clipped', 'A_normalized', 'H_normalized',
       'A_clipped_normalized', 'H_clipped_normalized', 'points',
       'avg_monthly_earnings_percentile', 'pct_men_percentile',
       'majority_race'],
      dtype='object')

In [77]:
access_df[['fpl_below', 'fpl_above']]

        fpl_below  fpl_above
0               0          1
1               0          1
2               0          1
3               0          1
4               1          0
...           ...        ...
301562          0          1
301563          0          1
301564          0          1
301565          0          1
301566          0          1

[301567 rows x 2 columns]

In [76]:
outcome_metrics = [
    'A', 'Q', 'H', 
    #'A_normalized', 'H_normalized', 
    #'A_percentile', 'Q_percentile', 'H_percentile',
    #'A_clipped_normalized', 'H_clipped_normalized',

]
access_df.describe()[outcome_metrics]

                   A              Q              H
count  281996.000000  281996.000000  281996.000000
mean        0.688919       0.402976       0.278384
std         0.609726       0.057715       0.215616
min         0.000379       0.150000       0.000133
25%         0.537793       0.360583       0.201500
50%         0.656696       0.408520       0.267733
75%         0.817793       0.443783       0.339502
max       176.032343       0.669369      42.185822

### Creating Access Metrics at different levels

In [78]:


agg_dict = {'sum':[
    'n_people',
    'n_households',
    'n_people_15to17_white', 'n_people_15to17_black',
       'n_people_15to17_asian', 'n_people_15to17_parda',
       'n_people_15to17_indigenous', 'n_people_15', 'n_people_16',
       'n_people_17', 'n_people_15_men', 'n_people_16_men', 'n_people_17_men',
       'n_people_15_women', 'n_people_16_women', 'n_people_17_women',
       'n_people_15to17dem', 'n_people_15to17_alternative'
       ], 

       'weighted_average':[
           'A', 'Q', 'H', 'A_normalized', 'H_normalized',
       'pct_black', 'pct_white', 'pct_indigenous', 'pct_pardos', 'pct_asian',
       'pct_men', 'avg_monthly_earnings', 'fpl_below'
       ]}

# Define a custom function for weighted average in a groupby, ignoring NaNs

In [79]:
# Renaming variables
access_df = access_df.rename(columns = {'city_id':'code_muni', 'microregion_id':'code_micro', 'state_id':'code_state'})

# Filling NaN values for the regions that do not have a school nearby
access_df[["A", "H"]] = access_df[["A", "H"]].fillna(0)

In [80]:
access_df[access_df['Q'].notna()]

,Unnamed: 0,sector_id,3sfca_n_classes,e2sfca_n_classes,state,n_households,n_people,avg_monthly_earnings,n_people_15to17_white,n_people_15to17_black,...,A_clipped,H_clipped,A_normalized,H_normalized,A_clipped_normalized,H_clipped_normalized,points,avg_monthly_earnings_percentile,pct_men_percentile,majority_race
0,0,170025105000002,0.002974,0.002974,TO,115.0,300.0,648.06,1.0,0.0,...,0.104084,0.044756,0.001582,0.001758,0.039272,0.001758,POINT (-49.01243434589464 -9.66749564036307),0.475728,0.944660,n_people_15to17_parda
1,1,170030105000001,0.037295,0.035309,TO,286.0,1123.0,927.45,10.0,2.0,...,1.305327,0.535184,0.020842,0.021920,0.517343,0.021920,MULTIPOINT (-47.48290111669609 -6.553566046310...,0.711165,0.433981,n_people_15to17_parda
2,2,170030105000002,0.037050,0.035869,TO,294.0,1101.0,478.33,11.0,0.0,...,1.296754,0.531669,0.020705,0.021775,0.513931,0.021775,MULTIPOINT (-47.46753706238716 -6.564822586025...,0.269903,0.506311,n_people_15to17_parda
3,3,170030105000003,0.007200,0.006643,TO,102.0,385.0,453.32,3.0,1.0,...,0.251988,0.103315,0.003954,0.004165,0.098135,0.004165,MULTIPOINT (-47.620756841496735 -6.44150741845...,0.237864,0.699029,n_people_15to17_parda
4,4,170030105000004,0.030753,0.038818,TO,56.0,245.0,368.55,3.0,0.0,...,1.076351,0.441304,0.017171,0.018060,0.426215,0.018060,POINT (-47.50298107795368 -6.560689654060223),0.141748,0.933981,n_people_15to17_parda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301562,301562,355620605000113,0.011941,0.004990,SP2,299.0,1083.0,1030.88,42.0,2.0,...,0.410790,0.200354,0.033316,0.031238,0.162414,0.031238,MULTIPOINT (-46.92693670311297 -22.96436255033...,0.427995,0.857477,n_people_15to17_white
301563,301563,355640405000064,0.017389,0.017229,SP2,45.0,163.0,914.44,3.0,1.0,...,0.606031,0.296775,0.049235,0.046362,0.240015,0.046362,NaN,0.326725,0.015572,n_people_15to17_white
301564,301564,355640405000070,0.020495,0.020317,SP2,224.0,811.0,779.52,24.0,3.0,...,0.714671,0.349828,0.058093,0.054683,0.283196,0.054683,MULTIPOINT (-46.89785537413103 -21.85002961708...,0.204819,0.737907,n_people_15to17_white
301565,301565,355645305000027,0.019816,0.014724,SP2,244.0,883.0,669.79,20.0,4.0,...,0.696824,0.310878,0.056638,0.048574,0.276103,0.048574,MULTIPOINT (-47.01994726148821 -23.59320273807...,0.117385,0.720962,n_people_15to17_parda
301566,301566,355680005000031,0.015391,0.015834,SP2,13.0,47.0,1110.77,2.0,0.0,...,0.539163,0.231833,0.043783,0.036176,0.213437,0.036176,NaN,0.488913,0.993868,n_people_15to17_white

In [87]:
def new_access_level(
        previous_level, 
        new_level_df, 
        new_level_name, 
        calculate_percentiles=['A', 'Q', 'H', 'avg_monthly_earnings', 'pct_men']
        ):

    def weighted_avg(group):
        weights = group['n_people_15to17']
        
        # Define numerical columns        
        weighted_averages = {}
        
        for col in agg_dict['weighted_average']:
            # Step 1: Mask for non-NaN values
            non_nan_mask = ~np.isnan(group[col])
            
            # Step 2: Apply mask to values and weights
            values_non_nan = group[col][non_nan_mask]
            weights_non_nan = weights[non_nan_mask]
            
            # Step 3: Check if sum of weights is zero
            if np.sum(weights_non_nan) == 0:
                weighted_averages[col] = np.nan
            else:
                # Step 4: Compute weighted average ignoring NaNs
                weighted_averages[col] = np.average(values_non_nan, weights=weights_non_nan)
        
        return pd.Series(weighted_averages)


    ## Group by 'Category'
    grouped = previous_level.groupby(new_level_name)

    # Calculate sum of 'Quantity' and 'Price'
    sum_columns = grouped[agg_dict['sum']].sum().reset_index()


    # Calculate weighted average of 'Value' using 'Weight'
    weighted_average = grouped.apply(weighted_avg).reset_index(drop=True)#[agg_dict['weighted_average']]

    # Combine the sum and weighted average DataFrames
    result_df = pd.concat([sum_columns, weighted_average], axis=1)

    new_level_access_df = result_df.merge(new_level_df, on=new_level_name, how='right')
    print(new_level_access_df.columns)
    # Calculate percentiles
    def add_percentile(access_df, cols, groupby = 'state_id'):
        for col in cols:
            access_df[f'{col}_percentile'] = access_df.groupby(groupby)[col].rank(pct=True)
        return access_df

    if calculate_percentiles:
        new_level_access_df = add_percentile(new_level_access_df, calculate_percentiles, groupby = 'code_state')
    
    new_level_access_df['majority_race'] = new_level_access_df[
        [f'n_people_15to17_{x}' for x in ['white', 'black', 'parda', 'asian', 'indigenous']]
        ].idxmax(axis=1)


    return new_level_access_df

In [88]:
# Values of Q that are not float
access_df[access_df['Q'].apply(lambda x: type(x) != float)]['Q']

Series([], Name: Q, dtype: float64)

In [89]:
# Municipality
municipalities_access_df = new_access_level(access_df, municipalities_df, 'code_muni')
municipalities_access_df.to_csv(f"{basepath}/municipality_access_df.csv", index=False)
municipalities_access_df.head()
print("Result DataFrame:")

Index(['code_muni', 'n_people', 'n_households', 'n_people_15to17_white',
       'n_people_15to17_black', 'n_people_15to17_asian',
       'n_people_15to17_parda', 'n_people_15to17_indigenous', 'n_people_15',
       'n_people_16', 'n_people_17', 'n_people_15_men', 'n_people_16_men',
       'n_people_17_men', 'n_people_15_women', 'n_people_16_women',
       'n_people_17_women', 'n_people_15to17dem',
       'n_people_15to17_alternative', 'A', 'Q', 'H', 'A_normalized',
       'H_normalized', 'pct_black', 'pct_white', 'pct_indigenous',
       'pct_pardos', 'pct_asian', 'pct_men', 'avg_monthly_earnings',
       'fpl_below', 'name_muni', 'code_state', 'abbrev_state', 'geometry'],
      dtype='object')
Result DataFrame:

In [94]:
# Microregion
microregion_access_df = new_access_level(access_df, microregion_df, 'code_micro')
print("Result DataFrame:")
microregion_access_df.to_csv(f"{basepath}/microregion_access_df.csv", index=False)
microregion_access_df.head()

Index(['code_micro', 'n_people', 'n_households', 'n_people_15to17_white',
       'n_people_15to17_black', 'n_people_15to17_asian',
       'n_people_15to17_parda', 'n_people_15to17_indigenous', 'n_people_15',
       'n_people_16', 'n_people_17', 'n_people_15_men', 'n_people_16_men',
       'n_people_17_men', 'n_people_15_women', 'n_people_16_women',
       'n_people_17_women', 'n_people_15to17dem',
       'n_people_15to17_alternative', 'A', 'Q', 'H', 'A_normalized',
       'H_normalized', 'pct_black', 'pct_white', 'pct_indigenous',
       'pct_pardos', 'pct_asian', 'pct_men', 'avg_monthly_earnings',
       'fpl_below', 'code_state', 'abbrev_state', 'name_state', 'name_micro',
       'geometry'],
      dtype='object')
Result DataFrame:

,code_micro,n_people,n_households,n_people_15to17_white,n_people_15to17_black,n_people_15to17_asian,n_people_15to17_parda,n_people_15to17_indigenous,n_people_15,n_people_16,...,abbrev_state,name_state,name_micro,geometry,A_percentile,Q_percentile,H_percentile,avg_monthly_earnings_percentile,pct_men_percentile,majority_race
0,11007.0,131293.0,40123.0,3079.0,406.0,74.0,4252.0,81.0,2678.0,2630.0,...,RO,Rondônia,Vilhena,"MULTIPOLYGON (((-60.44294 -11.01572, -60.43794...",1.000,0.125,0.750,0.875,0.125,n_people_15to17_parda
1,11001.0,530534.0,148820.0,8885.0,2084.0,632.0,20603.0,118.0,11058.0,10670.0,...,RO,Rondônia,Porto Velho,"MULTIPOLYGON (((-63.32721 -7.97672, -62.86662 ...",0.250,0.500,0.250,1.000,0.250,n_people_15to17_parda
2,11004.0,293414.0,89406.0,6225.0,1136.0,255.0,10467.0,87.0,6197.0,6111.0,...,RO,Rondônia,Ji-Paraná,"MULTIPOLYGON (((-61.57450 -9.72063, -61.57157 ...",0.375,0.625,0.375,0.750,0.375,n_people_15to17_parda
3,11002.0,69331.0,19056.0,1128.0,271.0,50.0,2784.0,274.0,1539.0,1533.0,...,RO,Rondônia,Guajará-Mirim,"MULTIPOLYGON (((-65.37724 -10.43117, -65.37505...",0.625,0.375,0.625,0.250,0.500,n_people_15to17_parda
4,11008.0,52293.0,16501.0,1294.0,218.0,46.0,1750.0,5.0,1126.0,1123.0,...,RO,Rondônia,Colorado Do Oeste,"MULTIPOLYGON (((-61.47607 -12.46432, -61.46801...",0.875,1.000,1.000,0.375,1.000,n_people_15to17_parda

In [95]:
# State
state_access_df = new_access_level(access_df, state_df, 'code_state', calculate_percentiles=False)
print("Result DataFrame:")
state_access_df.to_csv(f"{basepath}/state_access_df.csv", index=False)
state_access_df.head()

Index(['code_state', 'n_people', 'n_households', 'n_people_15to17_white',
       'n_people_15to17_black', 'n_people_15to17_asian',
       'n_people_15to17_parda', 'n_people_15to17_indigenous', 'n_people_15',
       'n_people_16', 'n_people_17', 'n_people_15_men', 'n_people_16_men',
       'n_people_17_men', 'n_people_15_women', 'n_people_16_women',
       'n_people_17_women', 'n_people_15to17dem',
       'n_people_15to17_alternative', 'A', 'Q', 'H', 'A_normalized',
       'H_normalized', 'pct_black', 'pct_white', 'pct_indigenous',
       'pct_pardos', 'pct_asian', 'pct_men', 'avg_monthly_earnings',
       'fpl_below', 'abbrev_state', 'name_state', 'code_region', 'name_region',
       'geometry'],
      dtype='object')
Result DataFrame:

,code_state,n_people,n_households,n_people_15to17_white,n_people_15to17_black,n_people_15to17_asian,n_people_15to17_parda,n_people_15to17_indigenous,n_people_15,n_people_16,...,pct_asian,pct_men,avg_monthly_earnings,fpl_below,abbrev_state,name_state,code_region,name_region,geometry,majority_race
0,11.0,1542048.0,454527.0,31306.0,5843.0,1441.0,56309.0,746.0,32671.0,32033.0,...,0.015065,0.503717,1065.369747,0.023743,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-63.32721 -7.97672, -62.86662 ...",n_people_15to17_parda
1,12.0,728754.0,190503.0,10833.0,2650.0,974.0,32430.0,1022.0,16875.0,15643.0,...,0.020330,0.500125,884.229632,0.170946,AC,Acre,1.0,Norte,"MULTIPOLYGON (((-73.18253 -7.33550, -72.58477 ...",n_people_15to17_parda
2,13.0,3457478.0,796959.0,45128.0,8402.0,1990.0,160085.0,11225.0,78681.0,75750.0,...,0.008773,0.501217,838.277639,0.185509,AM,Amazonas,1.0,Norte,"MULTIPOLYGON (((-67.32609 2.02971, -67.31682 2...",n_people_15to17_parda
3,14.0,445291.0,115320.0,5578.0,1463.0,261.0,18419.0,3274.0,10143.0,9588.0,...,0.009002,0.505397,993.262005,0.148060,RR,Roraima,1.0,Norte,"MULTIPOLYGON (((-60.20051 5.26434, -60.19273 5...",n_people_15to17_parda
4,15.0,7534979.0,1857406.0,98282.0,31570.0,4553.0,347443.0,2581.0,166139.0,161059.0,...,0.009399,0.504601,737.253953,0.240484,PA,Pará,1.0,Norte,"MULTIPOLYGON (((-54.95431 2.58369, -54.93542 2...",n_people_15to17_parda

In [96]:
access_df.geometry

0         POLYGON ((-49.147468339186396 -9.5742374934258...
1         POLYGON ((-47.4800002365659 -6.560778770862189...
2         POLYGON ((-47.46688024550971 -6.56653402083835...
3         POLYGON ((-47.467366454010794 -6.5392094162737...
4         POLYGON ((-47.503988774630905 -6.5605228596778...
                                ...
301562    POLYGON ((-46.925019817137 -22.971357095002794...
301563    POLYGON ((-46.943123513273 -21.863603277155505...
301564    POLYGON ((-46.896196 -21.850766999999998, -46....
301565    POLYGON ((-47.01548799999999 -23.5881979999999...
301566    POLYGON ((-48.310935254103 -20.874541774675205...
Name: geometry, Length: 301567, dtype: object

In [98]:
state_access_df

,code_state,n_people,n_households,n_people_15to17_white,n_people_15to17_black,n_people_15to17_asian,n_people_15to17_parda,n_people_15to17_indigenous,n_people_15,n_people_16,...,pct_asian,pct_men,avg_monthly_earnings,fpl_below,abbrev_state,name_state,code_region,name_region,geometry,majority_race
0,11.0,1542048.0,454527.0,31306.0,5843.0,1441.0,56309.0,746.0,32671.0,32033.0,...,0.015065,0.503717,1065.369747,0.023743,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-63.32721 -7.97672, -62.86662 ...",n_people_15to17_parda
1,12.0,728754.0,190503.0,10833.0,2650.0,974.0,32430.0,1022.0,16875.0,15643.0,...,0.020330,0.500125,884.229632,0.170946,AC,Acre,1.0,Norte,"MULTIPOLYGON (((-73.18253 -7.33550, -72.58477 ...",n_people_15to17_parda
2,13.0,3457478.0,796959.0,45128.0,8402.0,1990.0,160085.0,11225.0,78681.0,75750.0,...,0.008773,0.501217,838.277639,0.185509,AM,Amazonas,1.0,Norte,"MULTIPOLYGON (((-67.32609 2.02971, -67.31682 2...",n_people_15to17_parda
3,14.0,445291.0,115320.0,5578.0,1463.0,261.0,18419.0,3274.0,10143.0,9588.0,...,0.009002,0.505397,993.262005,0.148060,RR,Roraima,1.0,Norte,"MULTIPOLYGON (((-60.20051 5.26434, -60.19273 5...",n_people_15to17_parda
4,15.0,7534979.0,1857406.0,98282.0,31570.0,4553.0,347443.0,2581.0,166139.0,161059.0,...,0.009399,0.504601,737.253953,0.240484,PA,Pará,1.0,Norte,"MULTIPOLYGON (((-54.95431 2.58369, -54.93542 2...",n_people_15to17_parda
5,16.0,664346.0,156000.0,10644.0,3788.0,466.0,29880.0,551.0,15406.0,15311.0,...,0.010280,0.499283,1102.195433,0.040019,AP,Amapá,1.0,Norte,"MULTIPOLYGON (((-51.17970 4.00008, -51.17739 3...",n_people_15to17_parda
6,17.0,1375067.0,397788.0,18917.0,7232.0,1687.0,56780.0,870.0,29342.0,28268.0,...,0.019734,0.510130,948.397681,0.099408,TO,Tocantins,1.0,Norte,"MULTIPOLYGON (((-48.35878 -5.17008, -48.33846 ...",n_people_15to17_parda
7,21.0,6553441.0,1652188.0,86190.0,36103.0,4864.0,287784.0,2143.0,141556.0,140077.0,...,0.011662,0.502956,596.158224,0.420794,MA,Maranhão,2.0,Nordeste,"MULTIPOLYGON (((-45.84073 -1.04548, -45.84099 ...",n_people_15to17_parda
8,22.0,3101709.0,845803.0,42894.0,15293.0,3904.0,121360.0,166.0,64078.0,59998.0,...,0.021262,0.505492,670.272397,0.384610,PI,Piauí,2.0,Nordeste,"MULTIPOLYGON (((-41.74605 -2.80350, -41.73488 ...",n_people_15to17_parda
9,23.0,8375601.0,2350783.0,153083.0,21385.0,6808.0,339874.0,1211.0,182743.0,168820.0,...,0.013033,0.503177,671.401535,0.358586,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-41.16703 -4.46736, -41.17757 ...",n_people_15to17_parda
10,24.0,3152254.0,898060.0,71918.0,8526.0,2121.0,101853.0,142.0,64339.0,60679.0,...,0.011492,0.504643,840.172837,0.196617,RN,Rio Grande Do Norte,2.0,Nordeste,"MULTIPOLYGON (((-37.25329 -4.83156, -37.24905 ...",n_people_15to17_parda
11,25.0,3749985.0,1079895.0,80613.0,10803.0,2894.0,120061.0,1269.0,75659.0,70090.0,...,0.013420,0.506372,730.036107,0.305286,PB,Paraíba,2.0,Nordeste,"MULTIPOLYGON (((-37.22269 -6.04215, -37.21642 ...",n_people_15to17_parda
12,26.0,8749049.0,2544400.0,167554.0,28857.0,4811.0,289456.0,3357.0,172751.0,159274.0,...,0.009738,0.502372,732.906288,0.271870,PE,Pernambuco,2.0,Nordeste,"MULTIPOLYGON (((-32.39705 -3.83294, -32.39774 ...",n_people_15to17_parda
13,27.0,3095579.0,841844.0,57140.0,12118.0,2468.0,122393.0,921.0,69411.0,64067.0,...,0.012654,0.502805,678.745191,0.339018,AL,Alagoas,2.0,Nordeste,"MULTIPOLYGON (((-35.46753 -8.81744, -35.46430 ...",n_people_15to17_parda
14,28.0,2057483.0,590664.0,32161.0,10581.0,1695.0,80353.0,278.0,43279.0,42061.0,...,0.013553,0.502423,798.341538,0.255101,SE,Sergipe,2.0,Nordeste,"MULTIPOLYGON (((-37.99245 -9.52511, -37.98933 ...",n_people_15to17_parda
15,29.0,13947524.0,4089439.0,161410.0,135547.0,9680.0,509779.0,3212.0,281159.0,272675.0,...,0.011810,0.505180,685.701369,0.324072,BA,Bahia,2.0,Nordeste,"MULTIPOLYGON (((-39.36446 -8.53785, -39.35681 ...",n_people_15to17_parda
16,31.0,19457592.0,6015881.0,412800.0,93602.0,10294.0,521268.0,1743.0,357821.0,340667.0,...,0.009901,0.504782,1063.344038,0.055308,MG,Minas Gerais,3.0,Sudeste,"MULTIPOLYGON (((-41.87545 -20.76487, -41.87338...",n_people_15to17_parda
17,32.0,3484745.0,1097650.0,66596.0,14754.0,1206.0,99000.0,480.0,62400.0,59984.0,...,0.006625,0.502472,1148.690916,0.023237,ES,Espirito Santo,3.0,Sudeste,"MULTIPOLYGON (((-41.87545 -20.76487, -41.87920...",n_people_15to17_parda
18,33.0,15900229.0,5234713.0,317904.0,99327.0,6469.0,347853.0,680.0,266932.0,255022.0,...,0.008377,0.503329,1244.195253,0.020957,RJ,Rio De Janeiro,3.0,Sudeste,"MULTIPOLYGON (((-41.85946 -20.76517, -41.85748...",n_people_15to17_parda
19,35.0,40934060.0,12802649.0,1165345.0,108152.0,17709.0,694247.0,1899.0,682069.0,654343.0,...,0.008911,0.504328,1347.908849,0.013989,SP,São Paulo,3.0,Sudeste,"MULTIPOLYGON (((-44.90215 -23.35392, -44.90650...",n_people_15to17_white
20,41.0,10362668.0,3289682.0,374256.0,15848.0,4931.0,167977.0,1503.0,195388.0,185832.0,...,0.008735,0.507036,1219.267778,0.015427,PR,Paraná,4.0,Sul,"MULTIPOLYGON (((-52.05188 -22.53933, -52.03446...",n_people_15to17_white
21,42.0,6181215.0,1980677.0,262070.0,9959.0,1254.0,50001.0,1042.0,111484.0,106468.0,...,0.003866,0.505773,1342.814188,0.007024,SC,Santa Catarina,4.0,Sul,"MULTIPOLYGON (((-48.63865 -25.96873, -48.63434...",n_people_15to17_white
22,43.0,10569377.0,3578913.0,419658.0,33278.0,1744.0,72106.0,2145.0,184029.0,173737.0,...,0.003297,0.506718,1206.558376,0.014361,RS,Rio Grande Do Sul,4.0,Sul,"MULTIPOLYGON (((-51.90486 -27.45935, -51.90129...",n_people_15to17_white
23,50.0,2420098.0,757694.0,60048.0,6115.0,1401.0,65620.0,4890.0,47662.0,45696.0,...,0.010147,0.504809,1185.612202,0.046895,MS,Mato Grosso Do Sul,5.0,Centro Oeste,"MULTIPOLYGON (((-56.10370 -17.17354, -56.09692...",n_people_15to17_parda
24,51.0,2996721.0,910652.0,60050.0,12076.0,1849.0,97213.0,2595.0,59729.0,57743.0,...,0.010639,0.506563,1144.152394,0.031308,MT,Mato Grosso,5.0,Centro Oeste,"MULTIPOLYGON (((-54.89485 -17.62150, -54.89704...",n_people_15to17_parda
25,52.0,5961598.0,1883612.0,120124.0,19536.0,5768.0,176221.0,412.0,110636.0,105615.0,...,0.017909,0.502431,1186.982195,0.015065,GO,Goiás,5.0,Centro Oeste,"MULTIPOLYGON (((-50.16015 -12.42007, -50.15856...",n_people_15to17_parda
26,53.0,2555153.0,773326.0,48365.0,10123.0,2104.0,70659.0,286.0,45071.0,43170.0,...,0.015995,0.493820,2255.489707,0.005116,DF,Distrito Federal,5.0,Centro Oeste,"MULTIPOLYGON (((-47.57461 -15.51341, -47.56997...",n_people_15to17_parda